/**
 * Badge — Storybook stories
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Badge component set (30 variants) + Badge Number (19 variants)
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from '@/components/ui/badge';
import { BadgeNumber } from '@/components/ui/badge-number';

const meta: Meta<typeof Badge> = {
  title: 'UI/Badge',
  component: Badge,
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: [
        'default',
        'secondary',
        'destructive',
        'outline',
        'positive',
        'error',
        'warning',
        'neutral',
        'shortlist',
        'tag',
      ],
      description: 'Visual style — maps to Figma Variant dimension',
    },
  },
};
export default meta;
type Story = StoryObj<typeof Badge>;

// ─── Core variants ───────────────────────────────────────────────────────────

export const Default: Story = {
  args: { variant: 'default', children: 'Badge' },
};

export const Secondary: Story = {
  args: { variant: 'secondary', children: 'Badge' },
};

export const Destructive: Story = {
  args: { variant: 'destructive', children: 'Badge' },
};

export const Outline: Story = {
  args: { variant: 'outline', children: 'Badge' },
};

// ─── Semantic / status variants ──────────────────────────────────────────────

export const Positive: Story = {
  args: { variant: 'positive', children: 'Approved' },
};

export const Error: Story = {
  args: { variant: 'error', children: 'Failed' },
};

export const Warning: Story = {
  args: { variant: 'warning', children: 'Pending' },
};

export const Neutral: Story = {
  args: { variant: 'neutral', children: 'Draft' },
};

// ─── Selection / taxonomy variants ───────────────────────────────────────────

export const Shortlist: Story = {
  args: { variant: 'shortlist', children: 'Shortlisted' },
};

export const Tag: Story = {
  args: { variant: 'tag', children: 'Design Systems' },
};

// ─── All variants at a glance ─────────────────────────────────────────────────

export const AllVariants: Story = {
  name: 'All Variants',
  render: () => (
    <div className="flex flex-wrap gap-2">
      {(
        [
          'default',
          'secondary',
          'destructive',
          'outline',
          'positive',
          'error',
          'warning',
          'neutral',
          'shortlist',
          'tag',
        ] as const
      ).map((variant) => (
        <Badge key={variant} variant={variant}>
          {variant.charAt(0).toUpperCase() + variant.slice(1)}
        </Badge>
      ))}
    </div>
  ),
};

// ─── Badge Number ─────────────────────────────────────────────────────────────

export const NumberNeutral: StoryObj<typeof BadgeNumber> = {
  name: 'Number / Neutral',
  render: () => <BadgeNumber variant="neutral" count={4} />,
};

export const NumberPositive: StoryObj<typeof BadgeNumber> = {
  name: 'Number / Positive',
  render: () => <BadgeNumber variant="positive" count={12} />,
};

export const NumberError: StoryObj<typeof BadgeNumber> = {
  name: 'Number / Error',
  render: () => <BadgeNumber variant="error" count={3} />,
};

export const NumberWarning: StoryObj<typeof BadgeNumber> = {
  name: 'Number / Warning',
  render: () => <BadgeNumber variant="warning" count={7} />,
};

// ─── Playground ──────────────────────────────────────────────────────────────

export const Playground: Story = {
  args: { variant: 'default', children: 'Badge' },
};
