/**
 * Badge — TypeScript types
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Badge component set (30 variants) + Badge Number (19 variants)
 */
import type { ReactNode } from 'react';

/** 10 badge variants mapped from Figma Variant dimension */
export type BadgeVariant =
  | 'default'
  | 'secondary'
  | 'destructive'
  | 'outline'
  | 'positive'
  | 'error'
  | 'warning'
  | 'neutral'
  | 'shortlist'
  | 'tag';

export interface BadgeProps {
  /**
   * Visual style of the badge.
   * @default 'default'
   */
  variant?: BadgeVariant;
  children: ReactNode;
  className?: string;
}

/**
 * Badge Number — compact numeric badge.
 * Supports Neutral, Shortlist, Tag, Outline, Error, Positive, Warning variants only
 * (Default / Secondary / Destructive are not in the BadgeNumber Figma set).
 */
export type BadgeNumberVariant = Extract<
  BadgeVariant,
  'neutral' | 'shortlist' | 'tag' | 'outline' | 'error' | 'positive' | 'warning'
>;

export interface BadgeNumberProps {
  /**
   * Visual style of the number badge.
   * @default 'neutral'
   */
  variant?: BadgeNumberVariant;
  /** Numeric value displayed inside the badge */
  count: number;
  className?: string;
}
