/**
 * Button — Type definitions
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Button component set (156 variants)
 *
 * Figma dimensions:
 *   Variant × State × Size = 6 × 6 × 4 = 144 base + 12 icon-only = 156 total
 */

export type ButtonVariant =
  | 'default'
  | 'secondary'
  | 'ghost'
  | 'link'
  | 'outline'
  | 'destructive';

export type ButtonSize =
  | 'default'  // h-11, text-lg
  | 'sm'       // h-10, text-sm
  | 'lg'       // h-12, text-xl
  | 'icon';    // square, icon-only

export type ButtonState =
  | 'default'
  | 'hover'
  | 'focus'
  | 'loading'
  | 'disabled'
  | 'pressed';

export interface ButtonProps {
  /** Visual style variant */
  variant?: ButtonVariant;
  /** Button size */
  size?: ButtonSize;
  /** Disabled — maps to State=Disabled in Figma */
  disabled?: boolean;
  /** Show loading spinner — maps to State=Loading in Figma */
  loading?: boolean;
  /** Show icon on left side */
  showLeftIcon?: boolean;
  /** Show icon on right side */
  showRightIcon?: boolean;
  /** Button label */
  children?: React.ReactNode;
  /** Additional CSS classes */
  className?: string;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
}
