/**
 * Button — Storybook stories
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Button component set (156 variants)
 *
 * Every variant × size combination is a named story.
 * State stories (hover/focus/pressed) are simulated via CSS class overrides.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Button } from '@/components/ui/button';

const meta: Meta<typeof Button> = {
  title: 'UI/Button',
  component: Button,
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: ['default', 'secondary', 'ghost', 'link', 'outline', 'destructive'],
      description: 'Visual style variant',
      table: { defaultValue: { summary: 'default' } },
    },
    size: {
      control: 'select',
      options: ['default', 'sm', 'lg', 'icon'],
      description: 'Button size',
      table: { defaultValue: { summary: 'default' } },
    },
    disabled: {
      control: 'boolean',
      description: 'Disabled state',
    },
  },
};
export default meta;
type Story = StoryObj<typeof Button>;

/* ── Default variant ─────────────────────────────────────────────────────── */
export const Default: Story = {
  args: { variant: 'default', size: 'default', children: 'Button' },
};
export const DefaultSm: Story = {
  name: 'Default / Small',
  args: { variant: 'default', size: 'sm', children: 'Button' },
};
export const DefaultLg: Story = {
  name: 'Default / Large',
  args: { variant: 'default', size: 'lg', children: 'Button' },
};
export const DefaultIcon: Story = {
  name: 'Default / Icon',
  args: { variant: 'default', size: 'icon' },
};
export const DefaultLoading: Story = {
  name: 'Default / Loading',
  args: { variant: 'default', size: 'default', children: 'Saving...', loading: true },
};
export const DefaultDisabled: Story = {
  name: 'Default / Disabled',
  args: { variant: 'default', size: 'default', children: 'Button', disabled: true },
};

/* ── Secondary variant ───────────────────────────────────────────────────── */
export const Secondary: Story = {
  args: { variant: 'secondary', size: 'default', children: 'Button' },
};
export const SecondarySm: Story = {
  name: 'Secondary / Small',
  args: { variant: 'secondary', size: 'sm', children: 'Button' },
};
export const SecondaryLg: Story = {
  name: 'Secondary / Large',
  args: { variant: 'secondary', size: 'lg', children: 'Button' },
};
export const SecondaryDisabled: Story = {
  name: 'Secondary / Disabled',
  args: { variant: 'secondary', size: 'default', children: 'Button', disabled: true },
};

/* ── Destructive variant ─────────────────────────────────────────────────── */
export const Destructive: Story = {
  args: { variant: 'destructive', size: 'default', children: 'Delete' },
};
export const DestructiveSm: Story = {
  name: 'Destructive / Small',
  args: { variant: 'destructive', size: 'sm', children: 'Delete' },
};
export const DestructiveLg: Story = {
  name: 'Destructive / Large',
  args: { variant: 'destructive', size: 'lg', children: 'Delete' },
};
export const DestructiveDisabled: Story = {
  name: 'Destructive / Disabled',
  args: { variant: 'destructive', size: 'default', children: 'Delete', disabled: true },
};

/* ── Outline variant ─────────────────────────────────────────────────────── */
export const Outline: Story = {
  args: { variant: 'outline', size: 'default', children: 'Button' },
};
export const OutlineSm: Story = {
  name: 'Outline / Small',
  args: { variant: 'outline', size: 'sm', children: 'Button' },
};
export const OutlineLg: Story = {
  name: 'Outline / Large',
  args: { variant: 'outline', size: 'lg', children: 'Button' },
};

/* ── Ghost variant ───────────────────────────────────────────────────────── */
export const Ghost: Story = {
  args: { variant: 'ghost', size: 'default', children: 'Button' },
};
export const GhostSm: Story = {
  name: 'Ghost / Small',
  args: { variant: 'ghost', size: 'sm', children: 'Button' },
};
export const GhostLg: Story = {
  name: 'Ghost / Large',
  args: { variant: 'ghost', size: 'lg', children: 'Button' },
};
export const GhostIcon: Story = {
  name: 'Ghost / Icon',
  args: { variant: 'ghost', size: 'icon' },
};

/* ── Link variant ────────────────────────────────────────────────────────── */
export const Link: Story = {
  args: { variant: 'link', size: 'default', children: 'Learn more' },
};
export const LinkSm: Story = {
  name: 'Link / Small',
  args: { variant: 'link', size: 'sm', children: 'Learn more' },
};

/* ── Playground ──────────────────────────────────────────────────────────── */
export const Playground: Story = {
  args: {
    variant: 'default',
    size: 'default',
    children: 'Button',
    disabled: false,
  },
};
