/**
 * Checkbox — Storybook stories
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Checkbox component set (12 variants)
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from '@/components/ui/checkbox';

const meta: Meta<typeof Checkbox> = {
  title: 'UI/Checkbox',
  component: Checkbox,
  tags: ['autodocs'],
  argTypes: {
    checked: {
      control: 'select',
      options: [false, true, 'indeterminate'],
      description: 'Checked state — maps to Figma Status dimension',
    },
    disabled: {
      control: 'boolean',
    },
    label: {
      control: 'text',
    },
    description: {
      control: 'text',
    },
  },
};
export default meta;
type Story = StoryObj<typeof Checkbox>;

export const Unchecked: Story = {
  args: { checked: false, label: 'Accept terms' },
};
export const Checked: Story = {
  args: { checked: true, label: 'Accept terms' },
};
export const Indeterminate: Story = {
  args: { checked: 'indeterminate', label: 'Select all' },
};
export const WithDescription: Story = {
  name: 'With Description',
  args: {
    checked: false,
    label: 'Marketing emails',
    description: 'Receive emails about new products, features, and more.',
  },
};
export const DisabledUnchecked: Story = {
  name: 'Disabled / Unchecked',
  args: { checked: false, disabled: true, label: 'Accept terms' },
};
export const DisabledChecked: Story = {
  name: 'Disabled / Checked',
  args: { checked: true, disabled: true, label: 'Accept terms' },
};
export const DisabledIndeterminate: Story = {
  name: 'Disabled / Indeterminate',
  args: { checked: 'indeterminate', disabled: true, label: 'Select all' },
};
export const Playground: Story = {
  args: {
    checked: false,
    label: 'Label',
    disabled: false,
  },
};
