/**
 * Checkbox — Type definitions
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Checkbox component set (12 variants)
 *
 * Figma dimensions:
 *   Status (Active/Inactive/Indeterminate) × State (Default/Focus/Disabled/Pressed) = 12 variants
 */

export type CheckboxStatus = 'active' | 'inactive' | 'indeterminate';

export type CheckboxState = 'default' | 'focus' | 'disabled' | 'pressed';

export interface CheckboxProps {
  /** Checked state */
  checked?: boolean | 'indeterminate';
  /** Disabled */
  disabled?: boolean;
  /** Label displayed next to the checkbox */
  label?: string;
  /** Helper text below label */
  description?: string;
  /** Additional CSS classes */
  className?: string;
  onCheckedChange?: (checked: boolean | 'indeterminate') => void;
}
