/**
 * Input — Storybook stories
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Input component set (36 variants)
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Input } from '@/components/ui/input';

const meta: Meta<typeof Input> = {
  title: 'UI/Input',
  component: Input,
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: ['default', 'file'],
      description: 'Input type variant',
    },
    disabled: {
      control: 'boolean',
    },
    horizontal: {
      control: 'boolean',
      description: 'Inline label + input layout',
    },
    error: {
      control: 'text',
      description: 'Error message (triggers error state)',
    },
    success: {
      control: 'text',
      description: 'Success message (triggers success state)',
    },
  },
};
export default meta;
type Story = StoryObj<typeof Input>;

export const Default: Story = {
  args: { placeholder: 'Enter value...' },
};
export const WithLabel: Story = {
  name: 'With Label',
  args: { label: 'Email address', placeholder: 'you@example.com' },
};
export const Filled: Story = {
  args: { label: 'Email address', value: 'user@example.com' },
};
export const Focus: Story = {
  args: { label: 'Email address', placeholder: 'you@example.com', autoFocus: true },
};
export const Error: Story = {
  args: {
    label: 'Email address',
    value: 'not-an-email',
    error: 'Please enter a valid email address.',
  },
};
export const Success: Story = {
  args: {
    label: 'Email address',
    value: 'user@example.com',
    success: 'Looks good!',
  },
};
export const Disabled: Story = {
  args: { label: 'Email address', placeholder: 'you@example.com', disabled: true },
};
export const Horizontal: Story = {
  args: { label: 'Username', placeholder: 'johndoe', horizontal: true },
};
export const FileVariant: Story = {
  name: 'File Variant',
  args: { variant: 'file', label: 'Upload file' },
};
export const Playground: Story = {
  args: {
    label: 'Label',
    placeholder: 'Placeholder',
    disabled: false,
  },
};
