/**
 * Input — Type definitions
 * Generated by design-system-architect v2 · 2026-04-10
 * Source: Apollo v2.1 Input component set (36 variants)
 *
 * Figma dimensions:
 *   Horizontal Layout (No/Yes) × Variant (Default/File) × State (9) = 36 variants
 */

export type InputVariant = 'default' | 'file';

export type InputState =
  | 'default'
  | 'hover'
  | 'focus'
  | 'filled'
  | 'error'
  | 'error-focus'   // Error + focused simultaneously
  | 'success'
  | 'success-focus' // Success + focused simultaneously
  | 'disabled';

export interface InputProps {
  /** Input type (file variant enables file picker) */
  variant?: InputVariant;
  /** Controlled value */
  value?: string;
  /** Placeholder text */
  placeholder?: string;
  /** Field label — renders above the input */
  label?: string;
  /** Helper/hint text below input */
  helperText?: string;
  /** Error message — triggers error visual state */
  error?: string;
  /** Success message — triggers success visual state */
  success?: string;
  /** Disabled state */
  disabled?: boolean;
  /** Render label and input inline (horizontal layout) */
  horizontal?: boolean;
  /** Additional CSS classes */
  className?: string;
  onChange?: React.ChangeEventHandler<HTMLInputElement>;
}
