/**
 * RadioGroup / Radio Item — Storybook stories
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Radio / Item component set (16 variants)
 * Dimensions: Active(Off/On) × Type(Default/Box) × FontWeight(Medium/Regular) × State(Default/Focus)
 */
import type { Meta, StoryObj } from '@storybook/react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';

const meta: Meta<typeof RadioGroup> = {
  title: 'UI/RadioGroup',
  component: RadioGroup,
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean' },
  },
};
export default meta;
type Story = StoryObj<typeof RadioGroup>;

// ─── Type / Default ───────────────────────────────────────────────────────────

export const TypeDefault: Story = {
  name: 'Type / Default',
  render: () => (
    <RadioGroup defaultValue="weekly">
      {[
        { value: 'daily',   label: 'Daily digest' },
        { value: 'weekly',  label: 'Weekly summary' },
        { value: 'monthly', label: 'Monthly report' },
      ].map(({ value, label }) => (
        <div key={value} className="flex items-center gap-3">
          <RadioGroupItem value={value} id={`default-${value}`} />
          <Label htmlFor={`default-${value}`}>{label}</Label>
        </div>
      ))}
    </RadioGroup>
  ),
};

// ─── Type / Box ───────────────────────────────────────────────────────────────

export const TypeBox: Story = {
  name: 'Type / Box',
  render: () => (
    <RadioGroup defaultValue="pro" className="flex flex-col gap-2">
      {[
        { value: 'starter', label: 'Starter',     description: 'Up to 5 users, 10 projects' },
        { value: 'pro',     label: 'Pro',          description: 'Up to 25 users, unlimited projects' },
        { value: 'team',    label: 'Team',         description: 'Unlimited users and projects' },
      ].map(({ value, label, description }) => (
        <label
          key={value}
          htmlFor={`box-${value}`}
          className="flex items-start gap-3 rounded-xl border-2 border-border px-4 py-3 cursor-pointer
                     has-[:checked]:border-primary has-[:checked]:bg-secondary/30 transition-colors"
        >
          <RadioGroupItem value={value} id={`box-${value}`} className="mt-0.5" />
          <div>
            <p className="text-sm font-medium text-primary">{label}</p>
            <p className="text-xs text-muted-foreground">{description}</p>
          </div>
        </label>
      ))}
    </RadioGroup>
  ),
};

// ─── Font weight ──────────────────────────────────────────────────────────────

export const FontWeightMedium: Story = {
  name: 'Font Weight / Medium',
  render: () => (
    <RadioGroup defaultValue="option-a">
      {['Option A', 'Option B', 'Option C'].map((label, i) => (
        <div key={i} className="flex items-center gap-3">
          <RadioGroupItem value={`option-${String.fromCharCode(97 + i)}`} id={`fw-med-${i}`} />
          <Label htmlFor={`fw-med-${i}`} className="font-medium">{label}</Label>
        </div>
      ))}
    </RadioGroup>
  ),
};

export const FontWeightRegular: Story = {
  name: 'Font Weight / Regular',
  render: () => (
    <RadioGroup defaultValue="option-a">
      {['Option A', 'Option B', 'Option C'].map((label, i) => (
        <div key={i} className="flex items-center gap-3">
          <RadioGroupItem value={`option-${String.fromCharCode(97 + i)}`} id={`fw-reg-${i}`} />
          <Label htmlFor={`fw-reg-${i}`} className="font-normal">{label}</Label>
        </div>
      ))}
    </RadioGroup>
  ),
};

// ─── With descriptions ────────────────────────────────────────────────────────

export const WithDescriptions: Story = {
  name: 'With Descriptions',
  render: () => (
    <RadioGroup defaultValue="card">
      {[
        { value: 'card',   label: 'Card payment',    description: 'Visa, Mastercard, Amex' },
        { value: 'bank',   label: 'Bank transfer',   description: 'ACH direct debit, 2–3 business days' },
        { value: 'wallet', label: 'Digital wallet',  description: 'Apple Pay, Google Pay' },
      ].map(({ value, label, description }) => (
        <div key={value} className="flex items-start gap-3">
          <RadioGroupItem value={value} id={`desc-${value}`} className="mt-0.5" />
          <div>
            <Label htmlFor={`desc-${value}`} className="font-medium">{label}</Label>
            <p className="text-xs text-muted-foreground mt-0.5">{description}</p>
          </div>
        </div>
      ))}
    </RadioGroup>
  ),
};

// ─── Disabled ─────────────────────────────────────────────────────────────────

export const DisabledGroup: Story = {
  name: 'Disabled',
  render: () => (
    <RadioGroup defaultValue="weekly" disabled>
      {[
        { value: 'daily',   label: 'Daily digest' },
        { value: 'weekly',  label: 'Weekly summary' },
        { value: 'monthly', label: 'Monthly report' },
      ].map(({ value, label }) => (
        <div key={value} className="flex items-center gap-3">
          <RadioGroupItem value={value} id={`dis-${value}`} />
          <Label htmlFor={`dis-${value}`} className="text-muted-foreground">{label}</Label>
        </div>
      ))}
    </RadioGroup>
  ),
};

// ─── Playground ──────────────────────────────────────────────────────────────

export const Playground: Story = {
  render: (args) => (
    <RadioGroup defaultValue="option-a" disabled={args.disabled}>
      {['Option A', 'Option B', 'Option C'].map((label, i) => (
        <div key={i} className="flex items-center gap-3">
          <RadioGroupItem value={`option-${String.fromCharCode(97 + i)}`} id={`play-${i}`} />
          <Label htmlFor={`play-${i}`}>{label}</Label>
        </div>
      ))}
    </RadioGroup>
  ),
  args: { disabled: false },
};
