/**
 * RadioGroup / Radio Item — TypeScript types
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Radio / Item component set (16 variants)
 * Dimensions: Active(Off/On) × Type(Default/Box) × FontWeight(Medium/Regular) × State(Default/Focus)
 */

/**
 * Visual layout style of each radio option.
 * - 'default' — horizontal row: radio button + label/description
 * - 'box'     — full-width bordered card wrapping the option (used for prominent choices)
 */
export type RadioItemType = 'default' | 'box';

/**
 * Label font weight for the radio item.
 * - 'medium'  — 500 weight, standard form label
 * - 'regular' — 400 weight, lighter emphasis
 * @default 'medium'
 */
export type RadioFontWeight = 'medium' | 'regular';

export interface RadioItemProps {
  /** Whether this option is currently selected */
  checked: boolean;
  /**
   * Layout style of the radio option.
   * @default 'default'
   */
  type?: RadioItemType;
  /**
   * Label font weight.
   * @default 'medium'
   */
  fontWeight?: RadioFontWeight;
  /** Disables interaction (not a Figma variant — applied via opacity + pointer-events) */
  disabled?: boolean;
  /** Primary label text */
  label: string;
  /** Optional description text shown below the label */
  description?: string;
  /** Form value associated with this option */
  value: string;
  /** Change handler — called when this option is selected */
  onCheckedChange?: (value: string) => void;
  className?: string;
}

export interface RadioGroupProps {
  /** Currently selected value */
  value?: string;
  /** Change handler */
  onValueChange?: (value: string) => void;
  /** Radio options */
  children: React.ReactNode;
  /** Accessible group label */
  'aria-label'?: string;
  className?: string;
}
