/**
 * Select — TypeScript types
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Select component set (9 states) + Select Menu/Item (8 variants)
 */

/**
 * 9 visual states from the Figma Select component set.
 * Driven by value presence, focus, and validation feedback.
 */
export type SelectState =
  | 'default'
  | 'filled'
  | 'filledFocus'
  | 'focus'
  | 'disabled'
  | 'error'
  | 'errorFocus'
  | 'success'
  | 'successFocus';

export interface SelectProps {
  /** Placeholder text shown when no value is selected */
  placeholder?: string;
  /** Currently selected value */
  value?: string;
  /** Disables interaction — maps to State=Disabled */
  disabled?: boolean;
  /** Validation error message — triggers State=Error */
  error?: string;
  /** Validation success message — triggers State=Success */
  success?: string;
  /** Change handler */
  onValueChange?: (value: string) => void;
  className?: string;
}

/**
 * Select Menu Item — individual option row inside the Select dropdown.
 * Maps to the Select Menu/Item Figma component set (8 variants).
 */
export type SelectMenuItemType = 'simple' | 'icon';
export type SelectMenuItemVariant = 'default' | 'selected' | 'checkbox';

export interface SelectMenuItemProps {
  /**
   * Layout type — icon adds a leading icon slot.
   * @default 'simple'
   */
  type?: SelectMenuItemType;
  /**
   * Selection state of the item.
   * @default 'default'
   */
  variant?: SelectMenuItemVariant;
  /** Display label */
  label: string;
  /** Optional keyboard shortcut hint shown on the right */
  shortcut?: string;
  /** Leading icon (used when type='icon') */
  icon?: React.ReactNode;
  /** Whether the item is currently hovered */
  hovered?: boolean;
  onSelect?: () => void;
}
