/**
 * Select — Storybook stories
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Select component set (9 states) + Select Menu/Item (8 variants)
 */
import type { Meta, StoryObj } from '@storybook/react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

const meta: Meta<typeof Select> = {
  title: 'UI/Select',
  component: Select,
  tags: ['autodocs'],
  argTypes: {
    disabled: { control: 'boolean' },
  },
};
export default meta;
type Story = StoryObj<typeof Select>;

// Shared option set used across stories
const roleOptions = [
  { value: 'designer', label: 'Product Designer' },
  { value: 'engineer', label: 'Software Engineer' },
  { value: 'manager', label: 'Product Manager' },
  { value: 'researcher', label: 'UX Researcher' },
];

// ─── States ───────────────────────────────────────────────────────────────────

export const Default: Story = {
  name: 'State / Default',
  render: () => (
    <Select>
      <SelectTrigger className="w-64">
        <SelectValue placeholder="Select a role" />
      </SelectTrigger>
      <SelectContent>
        {roleOptions.map((o) => (
          <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  ),
};

export const Filled: Story = {
  name: 'State / Filled',
  render: () => (
    <Select defaultValue="designer">
      <SelectTrigger className="w-64">
        <SelectValue />
      </SelectTrigger>
      <SelectContent>
        {roleOptions.map((o) => (
          <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  ),
};

export const Disabled: Story = {
  name: 'State / Disabled',
  render: () => (
    <Select disabled>
      <SelectTrigger className="w-64">
        <SelectValue placeholder="Select a role" />
      </SelectTrigger>
      <SelectContent>
        {roleOptions.map((o) => (
          <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  ),
};

export const WithError: Story = {
  name: 'State / Error',
  render: () => (
    <div className="flex flex-col gap-1.5">
      <Select>
        <SelectTrigger className="w-64 border-destructive focus:ring-destructive">
          <SelectValue placeholder="Select a role" />
        </SelectTrigger>
        <SelectContent>
          {roleOptions.map((o) => (
            <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <p className="text-sm text-destructive">Please select a role to continue.</p>
    </div>
  ),
};

export const WithSuccess: Story = {
  name: 'State / Success',
  render: () => (
    <div className="flex flex-col gap-1.5">
      <Select defaultValue="designer">
        <SelectTrigger className="w-64 border-positive focus:ring-positive">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {roleOptions.map((o) => (
            <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <p className="text-sm text-positive">Looks good!</p>
    </div>
  ),
};

export const WithLabel: Story = {
  name: 'With Label',
  render: () => (
    <div className="flex flex-col gap-1.5">
      <label className="text-sm font-medium text-secondary">Role</label>
      <Select>
        <SelectTrigger className="w-64">
          <SelectValue placeholder="Select a role" />
        </SelectTrigger>
        <SelectContent>
          {roleOptions.map((o) => (
            <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  ),
};

// ─── Menu Item types ──────────────────────────────────────────────────────────

export const MenuItemSimple: Story = {
  name: 'Menu Item / Simple',
  render: () => (
    <Select defaultOpen>
      <SelectTrigger className="w-64">
        <SelectValue placeholder="Select a role" />
      </SelectTrigger>
      <SelectContent>
        {roleOptions.map((o) => (
          <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  ),
};

// ─── Playground ──────────────────────────────────────────────────────────────

export const Playground: Story = {
  render: (args) => (
    <Select disabled={args.disabled}>
      <SelectTrigger className="w-64">
        <SelectValue placeholder="Select a role" />
      </SelectTrigger>
      <SelectContent>
        {roleOptions.map((o) => (
          <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  ),
  args: { disabled: false },
};
