/**
 * Switch — TypeScript types
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Switch component set (16 variants)
 * Dimensions: Active(Off/On) × Type(Default/Box) × Side(Left/Right) × State(Default/Focus)
 */

/**
 * Visual style of the switch container.
 * - 'default' — standard pill toggle, no surrounding box
 * - 'box'     — toggle sits inside a bordered box (used in settings/form contexts)
 */
export type SwitchType = 'default' | 'box';

/**
 * Side the label appears relative to the toggle control.
 * - 'left'  — label leads, toggle follows
 * - 'right' — toggle leads, label follows
 * @default 'left'
 */
export type SwitchSide = 'left' | 'right';

export interface SwitchProps {
  /** Whether the switch is on */
  checked: boolean;
  /**
   * Visual container style.
   * @default 'default'
   */
  type?: SwitchType;
  /**
   * Label position relative to the toggle.
   * @default 'left'
   */
  side?: SwitchSide;
  /** Disables interaction (not a Figma variant — applied via opacity + pointer-events) */
  disabled?: boolean;
  /** Visible label text */
  label?: string;
  /** Optional description below the label */
  description?: string;
  /** Change handler */
  onCheckedChange?: (checked: boolean) => void;
  className?: string;
}
