/**
 * Switch — Storybook stories
 * Generated by design-system-architect v3 · 2026-04-13
 * Source: Apollo v2.1 Switch component set (16 variants)
 * Dimensions: Active(Off/On) × Type(Default/Box) × Side(Left/Right) × State(Default/Focus)
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';

const meta: Meta<typeof Switch> = {
  title: 'UI/Switch',
  component: Switch,
  tags: ['autodocs'],
  argTypes: {
    checked: { control: 'boolean' },
    disabled: { control: 'boolean' },
  },
};
export default meta;
type Story = StoryObj<typeof Switch>;

// ─── Active state ─────────────────────────────────────────────────────────────

export const Off: Story = {
  name: 'Active / Off',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-off" checked={false} />
      <Label htmlFor="switch-off">Email notifications</Label>
    </div>
  ),
};

export const On: Story = {
  name: 'Active / On',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-on" checked={true} />
      <Label htmlFor="switch-on">Email notifications</Label>
    </div>
  ),
};

// ─── Side ─────────────────────────────────────────────────────────────────────

export const LabelLeft: Story = {
  name: 'Side / Label Left',
  render: () => (
    <div className="flex items-center gap-3">
      <Label htmlFor="switch-left">Marketing emails</Label>
      <Switch id="switch-left" checked={false} />
    </div>
  ),
};

export const LabelRight: Story = {
  name: 'Side / Label Right',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-right" checked={true} />
      <Label htmlFor="switch-right">Product updates</Label>
    </div>
  ),
};

// ─── Type ─────────────────────────────────────────────────────────────────────

export const TypeDefault: Story = {
  name: 'Type / Default',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-default" checked={true} />
      <Label htmlFor="switch-default">Notifications</Label>
    </div>
  ),
};

export const TypeBox: Story = {
  name: 'Type / Box',
  render: () => (
    <div className="flex items-center justify-between rounded-xl border border-border px-4 py-3 w-80">
      <div>
        <p className="text-sm font-medium text-primary">Email notifications</p>
        <p className="text-xs text-muted-foreground">Receive updates about your account</p>
      </div>
      <Switch id="switch-box" checked={true} />
    </div>
  ),
};

// ─── Disabled ─────────────────────────────────────────────────────────────────

export const DisabledOff: Story = {
  name: 'Disabled / Off',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-dis-off" checked={false} disabled />
      <Label htmlFor="switch-dis-off" className="text-muted-foreground">Notifications (unavailable)</Label>
    </div>
  ),
};

export const DisabledOn: Story = {
  name: 'Disabled / On',
  render: () => (
    <div className="flex items-center gap-3">
      <Switch id="switch-dis-on" checked={true} disabled />
      <Label htmlFor="switch-dis-on" className="text-muted-foreground">Required setting</Label>
    </div>
  ),
};

// ─── All variants ─────────────────────────────────────────────────────────────

export const AllVariants: Story = {
  name: 'All Variants',
  render: () => (
    <div className="flex flex-col gap-4">
      {[
        { checked: false, label: 'Off — Default' },
        { checked: true,  label: 'On — Default' },
        { checked: false, label: 'Off — Disabled', disabled: true },
        { checked: true,  label: 'On — Disabled', disabled: true },
      ].map(({ checked, label, disabled }, i) => (
        <div key={i} className="flex items-center gap-3">
          <Switch checked={checked} disabled={disabled} />
          <Label className={disabled ? 'text-muted-foreground' : ''}>{label}</Label>
        </div>
      ))}
    </div>
  ),
};

// ─── Playground ──────────────────────────────────────────────────────────────

export const Playground: Story = {
  args: { checked: false, disabled: false },
};
