/**
 * Apollo v2.1 — Tailwind Theme Extension
 * Generated by design-system-architect v2 · 2026-04-10
 *
 * Drop into tailwind.config.js / tailwind.config.ts:
 *
 *   const apolloTokens = require('./design-system/tokens/tailwind.tokens');
 *
 *   module.exports = {
 *     theme: {
 *       extend: {
 *         ...apolloTokens,
 *       },
 *     },
 *   };
 *
 * Requires tokens.css to be imported in your app root for CSS variables to resolve.
 */

/** @type {import('tailwindcss').Config['theme']} */
module.exports = {
  colors: {
    accent:                    'var(--color-accent)',
    'accent-foreground':       'var(--color-accent-foreground)',
    background:                'var(--color-background)',
    border:                    'var(--color-border)',
    card:                      'var(--color-card)',
    'card-foreground':         'var(--color-card-foreground)',
    destructive:               'var(--color-destructive)',
    'destructive-foreground':  'var(--color-destructive-foreground)',
    foreground:                'var(--color-foreground)',
    input:                     'var(--color-input)',
    positive:                  'var(--color-positive)',
    neutral:                   'var(--color-neutral)',
    negative:                  'var(--color-negative)',
    brand:                     'var(--color-brand)',
    muted:                     'var(--color-muted)',
    'muted-foreground':        'var(--color-muted-foreground)',
    popover:                   'var(--color-popover)',
    'popover-foreground':      'var(--color-popover-foreground)',
    primary:                   'var(--color-primary)',
    'primary-foreground':      'var(--color-primary-foreground)',
    ring:                      'var(--color-ring)',
    'ring-offset':             'var(--color-ring-offset)',
    secondary:                 'var(--color-secondary)',
    'secondary-foreground':    'var(--color-secondary-foreground)',
    overlay:                   'var(--color-overlay)',
    sidebar:                   'var(--color-sidebar)',
    'sidebar-foreground':      'var(--color-sidebar-foreground)',
    'sidebar-primary':         'var(--color-sidebar-primary)',
    'sidebar-primary-foreground': 'var(--color-sidebar-primary-foreground)',
    'sidebar-accent':          'var(--color-sidebar-accent)',
    'sidebar-accent-foreground': 'var(--color-sidebar-accent-foreground)',
    'sidebar-border':          'var(--color-sidebar-border)',
    'sidebar-ring':            'var(--color-sidebar-ring)',
    chart: {
      1:                       'var(--color-chart-1)',
      2:                       'var(--color-chart-2)',
      3:                       'var(--color-chart-3)',
      4:                       'var(--color-chart-4)',
      5:                       'var(--color-chart-5)',
    },
    alpha: {
      5:                       'var(--color-alpha-5)',
      10:                      'var(--color-alpha-10)',
      20:                      'var(--color-alpha-20)',
      30:                      'var(--color-alpha-30)',
      40:                      'var(--color-alpha-40)',
      50:                      'var(--color-alpha-50)',
      60:                      'var(--color-alpha-60)',
      70:                      'var(--color-alpha-70)',
      80:                      'var(--color-alpha-80)',
      90:                      'var(--color-alpha-90)',
    },
  },
  borderRadius: {
    none:   'var(--radius-none)',
    xs:     'var(--radius-xs)',
    sm:     'var(--radius-sm)',
    DEFAULT:'var(--radius-md)',
    md:     'var(--radius-md)',
    lg:     'var(--radius-lg)',
    xl:     'var(--radius-xl)',
    '2xl':  'var(--radius-2xl)',
    '3xl':  'var(--radius-3xl)',
    '4xl':  'var(--radius-4xl)',
    full:   'var(--radius-full)',
  },
  transitionDuration: {
    75:     'var(--motion-duration-75)',
    100:    'var(--motion-duration-100)',
    150:    'var(--motion-duration-150)',
    200:    'var(--motion-duration-200)',
    300:    'var(--motion-duration-300)',
    500:    'var(--motion-duration-500)',
    700:    'var(--motion-duration-700)',
  },
  transitionTimingFunction: {
    linear:  'var(--motion-ease-linear)',
    in:      'var(--motion-ease-in)',
    out:     'var(--motion-ease-out)',
    'in-out':'var(--motion-ease-in-out)',
  },
  zIndex: {
    0:       'var(--z-0)',
    10:      'var(--z-10)',
    20:      'var(--z-20)',
    30:      'var(--z-30)',
    40:      'var(--z-40)',
    50:      'var(--z-50)',
  },
};
