/**
 * Apollo v2.1 — Design Token Map
 * Generated by design-system-architect v2 · 2026-04-10
 *
 * All values reference CSS custom properties defined in tokens.css.
 * Import tokens.css in your app root, then use these constants for type-safe token access.
 *
 * @example
 * import { tokens } from './tokens';
 * // tokens.color.primary → 'var(--color-primary)'
 */

export const tokens = {
  color: {
    accent:                   'var(--color-accent)',
    accentForeground:         'var(--color-accent-foreground)',
    background:               'var(--color-background)',
    border:                   'var(--color-border)',
    card:                     'var(--color-card)',
    cardForeground:           'var(--color-card-foreground)',
    destructive:              'var(--color-destructive)',
    destructiveForeground:    'var(--color-destructive-foreground)',
    foreground:               'var(--color-foreground)',
    input:                    'var(--color-input)',
    positive:                 'var(--color-positive)',
    neutral:                  'var(--color-neutral)',
    negative:                 'var(--color-negative)',
    brand:                    'var(--color-brand)',
    muted:                    'var(--color-muted)',
    mutedForeground:          'var(--color-muted-foreground)',
    popover:                  'var(--color-popover)',
    popoverForeground:        'var(--color-popover-foreground)',
    primary:                  'var(--color-primary)',
    primaryForeground:        'var(--color-primary-foreground)',
    ring:                     'var(--color-ring)',
    ringOffset:               'var(--color-ring-offset)',
    secondary:                'var(--color-secondary)',
    secondaryForeground:      'var(--color-secondary-foreground)',
    overlay:                  'var(--color-overlay)',
    sidebar: {
      DEFAULT:                'var(--color-sidebar)',
      foreground:             'var(--color-sidebar-foreground)',
      primary:                'var(--color-sidebar-primary)',
      primaryForeground:      'var(--color-sidebar-primary-foreground)',
      accent:                 'var(--color-sidebar-accent)',
      accentForeground:       'var(--color-sidebar-accent-foreground)',
      border:                 'var(--color-sidebar-border)',
      ring:                   'var(--color-sidebar-ring)',
    },
    chart: {
      1:                      'var(--color-chart-1)',
      2:                      'var(--color-chart-2)',
      3:                      'var(--color-chart-3)',
      4:                      'var(--color-chart-4)',
      5:                      'var(--color-chart-5)',
    },
    alpha: {
      5:                      'var(--color-alpha-5)',
      10:                     'var(--color-alpha-10)',
      20:                     'var(--color-alpha-20)',
      30:                     'var(--color-alpha-30)',
      40:                     'var(--color-alpha-40)',
      50:                     'var(--color-alpha-50)',
      60:                     'var(--color-alpha-60)',
      70:                     'var(--color-alpha-70)',
      80:                     'var(--color-alpha-80)',
      90:                     'var(--color-alpha-90)',
    },
  },
  spacing: {
    0:    'var(--spacing-0)',
    px:   'var(--spacing-px)',
    '0-5':'var(--spacing-0-5)',
    1:    'var(--spacing-1)',
    '1-5':'var(--spacing-1-5)',
    2:    'var(--spacing-2)',
    '2-5':'var(--spacing-2-5)',
    3:    'var(--spacing-3)',
    '3-5':'var(--spacing-3-5)',
    4:    'var(--spacing-4)',
    5:    'var(--spacing-5)',
    6:    'var(--spacing-6)',
    7:    'var(--spacing-7)',
    8:    'var(--spacing-8)',
    9:    'var(--spacing-9)',
    10:   'var(--spacing-10)',
    11:   'var(--spacing-11)',
    12:   'var(--spacing-12)',
    14:   'var(--spacing-14)',
    16:   'var(--spacing-16)',
    20:   'var(--spacing-20)',
    24:   'var(--spacing-24)',
    28:   'var(--spacing-28)',
    32:   'var(--spacing-32)',
    36:   'var(--spacing-36)',
    40:   'var(--spacing-40)',
    44:   'var(--spacing-44)',
    48:   'var(--spacing-48)',
    52:   'var(--spacing-52)',
    56:   'var(--spacing-56)',
    60:   'var(--spacing-60)',
    64:   'var(--spacing-64)',
    72:   'var(--spacing-72)',
    80:   'var(--spacing-80)',
    96:   'var(--spacing-96)',
  },
  borderRadius: {
    none:   'var(--radius-none)',
    xs:     'var(--radius-xs)',
    sm:     'var(--radius-sm)',
    md:     'var(--radius-md)',
    lg:     'var(--radius-lg)',
    xl:     'var(--radius-xl)',
    '2xl':  'var(--radius-2xl)',
    '3xl':  'var(--radius-3xl)',
    '4xl':  'var(--radius-4xl)',
    full:   'var(--radius-full)',
  },
  motion: {
    duration: {
      75:   'var(--motion-duration-75)',
      100:  'var(--motion-duration-100)',
      150:  'var(--motion-duration-150)',
      200:  'var(--motion-duration-200)',
      300:  'var(--motion-duration-300)',
      500:  'var(--motion-duration-500)',
      700:  'var(--motion-duration-700)',
    },
    ease: {
      linear:   'var(--motion-ease-linear)',
      in:       'var(--motion-ease-in)',
      out:      'var(--motion-ease-out)',
      inOut:    'var(--motion-ease-in-out)',
    },
  },
  zIndex: {
    0:    'var(--z-0)',
    10:   'var(--z-10)',
    20:   'var(--z-20)',
    30:   'var(--z-30)',
    40:   'var(--z-40)',
    50:   'var(--z-50)',
  },
} as const;

export type TokenColor = keyof typeof tokens.color;
export type TokenSpacing = keyof typeof tokens.spacing;
export type TokenBorderRadius = keyof typeof tokens.borderRadius;
export type TokenMotionDuration = keyof typeof tokens.motion.duration;
export type TokenMotionEase = keyof typeof tokens.motion.ease;
export type TokenZIndex = keyof typeof tokens.zIndex;
